name: My workflowWW
on:
 workflow_dispatch

jobs:
 my-first-job:
  runs-on: ubuntu-latest
  steps:
  - run: echo "Hello world" 

 my-second-job:
  runs-on: ubuntu-latest
  steps:
  - run: echo "Bye world" 
